### ISSUE TITLE
Support for additionalProperties in CRD Annotations with cty

### ISSUE THREAD

**Issue by henrysachs** [Skarlso/crd-to-sample-yaml#93]
Hello,

I recently attempted to add annotations, similar to the native Kubernetes annotations, to my Custom Resource Definition (CRD). Since annotations are essentially random key-value pairs, I explored using additionalProperties as outlined in the OpenAPI documentation [here](https://swagger.io/docs/specification/data-models/dictionaries/).

However, when I tried to implement this in my YAML configuration, I encountered a SIGSEGV error with cty. Could cty be updated to support the use of additionalProperties for CRD annotations? It would be a great enhancement and provide more flexibility.

Thank you!

this is a snippet from my crd:

```yaml
                values:
                  description: all values for the helm chart
                  properties:
                    teams:
                      properties:
                        annotations:
                          additionalProperties: true
                          description: Annotations set to all Kubernetes components
                          type: object
```

here is the stacktrace if helpful
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x168 pc=0x1515f3f]

goroutine 1 [running]:
github.com/Skarlso/crd-to-sample-yaml/pkg.ParseProperties({0xc0001db690, 0xe}, {0xc0001db6e0, 0x8}, {0xc0001db6a0, 0xb}, 0xc0001d1710, {0x16f55e0, 0xc000066cc8}, 0x6, ...)
        github.com/Skarlso/crd-to-sample-yaml/pkg/generate.go:106 +0xabf
github.com/Skarlso/crd-to-sample-yaml/pkg.ParseProperties({0xc0001db690, 0xe}, {0xc0001db6e0, 0x8}, {0xc0001db6a0, 0xb}, 0xc0001d16e0, {0x16f55e0, 0xc000066cc8}, 0x4, ...)
        github.com/Skarlso/crd-to-sample-yaml/pkg/generate.go:102 +0xcf6
github.com/Skarlso/crd-to-sample-yaml/pkg.ParseProperties({0xc0001db690, 0xe}, {0xc0001db6e0, 0x8}, {0xc0001db6a0, 0xb}, 0xc0001d1680, {0x16f55e0, 0xc000066cc8}, 0x2, ...)
        github.com/Skarlso/crd-to-sample-yaml/pkg/generate.go:102 +0xcf6
github.com/Skarlso/crd-to-sample-yaml/pkg.ParseProperties({0xc0001db690, 0xe}, {0xc0001db6e0, 0x8}, {0xc0001db6a0, 0xb}, 0xc0001d1620, {0x16f55e0, 0xc000066cc8}, 0x0, ...)
        github.com/Skarlso/crd-to-sample-yaml/pkg/generate.go:102 +0xcf6
github.com/Skarlso/crd-to-sample-yaml/pkg.Generate(0xc0001538c0, {0x16f73a8?, 0xc000066cc8}, 0xba?)
        github.com/Skarlso/crd-to-sample-yaml/pkg/generate.go:22 +0x208
github.com/Skarlso/crd-to-sample-yaml/cmd.runGenerate(0xc000166a00?, {0x1611e90?, 0x4?, 0x1611e94?})
        github.com/Skarlso/crd-to-sample-yaml/cmd/generate.go:85 +0x285
github.com/spf13/cobra.(*Command).execute(0x1ab7b20, {0xc000040d70, 0x5, 0x5})
        github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0x1ab7e00)
        github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/Skarlso/crd-to-sample-yaml/cmd.Execute(...)
        github.com/Skarlso/crd-to-sample-yaml/cmd/root.go:18
main.main()
        github.com/Skarlso/crd-to-sample-yaml/main.go:10 +0x1a
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x168 pc=0x1515f3f]

goroutine 1 [running]:
github.com/Skarlso/crd-to-sample-yaml/pkg.ParseProperties({0xc0001cfa90, 0xe}, {0xc0001cfad0, 0x8}, {0xc0001cfaa0, 0xf}, 0xc0001c3e00, {0x16f55e0, 0xc000066cd0}, 0x6, ...)
        github.com/Skarlso/crd-to-sample-yaml/pkg/generate.go:106 +0xabf
github.com/Skarlso/crd-to-sample-yaml/pkg.ParseProperties({0xc0001cfa90, 0xe}, {0xc0001cfad0, 0x8}, {0xc0001cfaa0, 0xf}, 0xc0001c3dd0, {0x16f55e0, 0xc000066cd0}, 0x4, ...)
        github.com/Skarlso/crd-to-sample-yaml/pkg/generate.go:102 +0xcf6
github.com/Skarlso/crd-to-sample-yaml/pkg.ParseProperties({0xc0001cfa90, 0xe}, {0xc0001cfad0, 0x8}, {0xc0001cfaa0, 0xf}, 0xc0001c3d70, {0x16f55e0, 0xc000066cd0}, 0x2, ...)
        github.com/Skarlso/crd-to-sample-yaml/pkg/generate.go:102 +0xcf6
github.com/Skarlso/crd-to-sample-yaml/pkg.ParseProperties({0xc0001cfa90, 0xe}, {0xc0001cfad0, 0x8}, {0xc0001cfaa0, 0xf}, 0xc0001c3d10, {0x16f55e0, 0xc000066cd0}, 0x0, ...)
        github.com/Skarlso/crd-to-sample-yaml/pkg/generate.go:102 +0xcf6
github.com/Skarlso/crd-to-sample-yaml/pkg.Generate(0xc0001538c0, {0x16f73a8?, 0xc000066cd0}, 0xba?)
        github.com/Skarlso/crd-to-sample-yaml/pkg/generate.go:22 +0x208
github.com/Skarlso/crd-to-sample-yaml/cmd.runGenerate(0xc000166a00?, {0x1611e90?, 0x4?, 0x1611e94?})
        github.com/Skarlso/crd-to-sample-yaml/cmd/generate.go:85 +0x285
github.com/spf13/cobra.(*Command).execute(0x1ab7b20, {0xc000040d70, 0x5, 0x5})
        github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0x1ab7e00)
        github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/Skarlso/crd-to-sample-yaml/cmd.Execute(...)
        github.com/Skarlso/crd-to-sample-yaml/cmd/root.go:18
main.main()
        github.com/Skarlso/crd-to-sample-yaml/main.go:10 +0x1a
```

**Comment by Skarlso** [comment]
Oh interesting! Thanks very much for the report. I'll check it out. :)

**Comment by Skarlso** [comment]
@henrysachs Which version where you trying out?

**Comment by henrysachs** [comment]
@Skarlso the tool doesnt print out its version (so maybe i have a really old one 😅)
we also found a "workaround" when specifying the type of `additionalproperties` it seems to work only when using `true` as value it fails

```
❯ cty help
CRDs to a Sample file.

Usage:
  crd-to-sample [flags]
  crd-to-sample [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  generate    Simply generate a CRD output.
  help        Help about any command

Flags:
  -h, --help   help for crd-to-sample

Use "crd-to-sample [command] --help" for more information about a command.
```

**Comment by Skarlso** [comment]
Oh, it is quite old then. :D 

```
./cty version
v0.0.0-dev
➜  crd-to-sample-yaml git:(main) ✗
```

Should have a version now. :)

In any case, I just successfully reproduced your error. So I'll be fixing it shortly. :) Thank you 🙇

**Comment by Skarlso** [comment]
Yah, I was missing a check to see if Schema was defined. :)

**Comment by Skarlso** [comment]
Your version will be v0.7.1 :)

**Comment by henrysachs** [comment]
I tried it out. Works like a charm thanks for the fast fix! <3
